version: '3.0'

services:
  rails-shop:
    build: .
    restart: always
    ports:
      - "80:3000"
    container_name: demo_shop
    volumes:
      - rails:/demo_shop
volumes:
  rails:
   driver_opts:
      type: none
      device: /demo_shop
      o: bind
